gulu:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: gulu_town
    username: root
    password: root
spring:
  redis:
    port: 6379
    host: localhost
    database: 1
