server:
  port: 8080
spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      #      数据库配置
      driver-class-name: ${gulu.datasource.driver-class-name}
      url: jdbc:mysql://${gulu.datasource.host}:${gulu.datasource.port}/${gulu.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${gulu.datasource.username}
      password: ${gulu.datasource.password}
  redis:
    #    redis配置
    host: ${spring.redis.host}
    port: ${spring.redis.port}
    database: ${spring.redis.database}
  #    邮件发送配置
  mail:
    host: smtp.163.com
    port: 465
    password: XCUVBHusuAWHKujn
    username: 18904451584@163.com
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
            required: false
        debug: false
    protocol: smtp

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.gulutown.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
auto:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: auto_town
    # 设置jwt过期时间
    admin-ttl: 7200000000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
  # 阿里对象存储oss
  oss:
    endpoint: ${auto.oss.endpoint}
    access-key-id: ${auto.oss.access-key-id}
    access-key-secret: ${auto.oss.access-key-secret}
    bucket-name: ${auto.oss.bucket-name}
# 开启mybatis日志
logging:
  level:
    com:
      gulutown:
        mapper: debug
        service: info
        controller: info